package xj.mobile.model

/*
 *  Generated by xj.mobile.tool.ProcessType
 *  Created on: Wed Dec 11 11:19:25 CST 2013
 */
class PropertyContextMap { 

  static contextMap = [
	Alert: [
		alertViewStyle: 'AlertViewStyle'
	],
	Text: [
		keyboardType: 'KeyboardType'
	],
	Button: [
		transition: 'ModalTransitionStyle'
	],
	onShake: [
		transition: 'ModalTransitionStyle'
	],
	onTouch: [
		transition: 'ModalTransitionStyle'
	],
	onDrag: [
		transition: 'ModalTransitionStyle'
	],
	onSwipe: [
		transition: 'ModalTransitionStyle',
		direction: 'SwipeGestureRecognizerDirection'
	],
	onPinch: [
		transition: 'ModalTransitionStyle'
	],
	onTap: [
		transition: 'ModalTransitionStyle'
	],
	onDoubleTap: [
		transition: 'ModalTransitionStyle'
	],
	onRotation: [
		transition: 'ModalTransitionStyle'
	],
	onLongPress: [
		transition: 'ModalTransitionStyle'
	],
	onMotion: [
		transition: 'ModalTransitionStyle'
	],
	onOrientationChange: [
		transition: 'ModalTransitionStyle'
	],
	onDeviceOrientationChange: [
		transition: 'ModalTransitionStyle'
	],
	onFling: [
		direction: 'SwipeGestureRecognizerDirection'
	]
  ]

}
